[echo]
usage  ="Echoes stdin to stdout"
example="echo 'Hello, World!'"
output ="Hello, World!"

[pwd]
usage  ="Prints the current working directory"
example="pwd"
output ="/home/user"

[ls]
usage  ="Lists files in the current directory"
example="ls"
output ="file1.txt\nfile2.txt\ndir1\ndir2"
[ls.flags]
-l="Use a long listing format"
-a="Include hidden files"

[touch]
usage="Creates an empty file"
[touch.example]
example="touch newfile.txt"
note   ="Creates a new file named newfile.txt if it does not exist, and it updates the timestamp if it does exist"

[file]
usage        ="Displays file information"
example      ="file example.txt"
exampleOutput="example.txt: ASCII text"

[less]
usage        ="View the contents of a file one screen at a time"
example      ="less example.txt"
exampleOutput="Displays the contents of example.txt with pagination"

[wildcards]
usage="can be used to match multiple files"
wildcards.symbols=[
    {symbol="*", description="Matches any number of characters"},
    {symbol="?", description="Matches a single character"},
    {symbol="[]", description="Matches any character in the brackets"},
]

[cp]
